export enum Obcine {
	Maribor = 'Maribor',
	Benedikt = 'Benedikt',
	Cerkvenjak = 'Cerkvenjak',
	Duplek = 'Duplek',
	HoceSlivnica = 'Hoče-Slivnica',
	Kungota = 'Kungota',
	Lenart = 'Lenart',
	LovrencNaPohorju = 'Lovrenc na Pohorju',
	MiklavzNaDravskemPolju = 'Miklavž na Dravskem polju',
	Pesnica = 'Pesnica',
	RaceFram = 'Rače-Fram',
	Ruse = 'Ruše',
	SelnicaObDravi = 'Selnica ob Dravi',
	Starse = 'Starše',
	SvetaTrojica = 'Sveta Trojica',
	SvetaAna = 'Sveta Ana',
	SvetiJurijVSlovenskihGoricah = 'Sveti Jurij v Slovenskih goricah',
	Sentilj = 'Šentilj',

	// Prosim naj mi nekdo oprosti za to grozoto
	'Hoče-Slivnica' = 'HoceSlivnica',
	'Lovrenc na Pohorju' = 'LovrencNaPohorju',
	'Miklavž na Dravskem polju' = 'MiklavzNaDravskemPolju',
	'Rače-Fram' = 'RaceFram',
	'Ruše' = 'Ruse',
	'Selnica ob Dravi' = 'SelnicaObDravi',
	'Starše' = 'Starse',
	'Sveta Trojica' = 'SvetaTrojica',
	'Sveta Ana' = 'SvetaAna',
	'Sveti Jurij v Slovenskih goricah' = 'SvetiJurijVSlovenskihGoricah',
	'Šentilj' = 'Sentilj'
}
